const footballRanking=[
{
"position":1,
"flag_img":"https://cloudinary.fifa.com/api/v1/picture/flags-sq-5/BRA?tx=c_fill,g_auto,q_auto,w_200",
"name":"Brazil"
},
{
"position":2,
"flag_img":"https://cloudinary.fifa.com/api/v1/picture/flags-sq-5/BEL?tx=c_fill,g_auto,q_auto,w_200",
"name":"Belgium"
},
{
"position":3,
"flag_img":"https://cloudinary.fifa.com/api/v1/picture/flags-sq-5/FRA?tx=c_fill,g_auto,q_auto,w_200",
"name":"France"
},
{
"position":4,
"flag_img":"https://cloudinary.fifa.com/api/v1/picture/flags-sq-5/ARG?tx=c_fill,g_auto,q_auto,w_200",
"name":"Argentina"
},
{
"position":5,
"flag_img":"https://cloudinary.fifa.com/api/v1/picture/flags-sq-5/ENG?tx=c_fill,g_auto,q_auto,w_200",
"name":"England"
},
{
"position":6,
"flag_img":"https://cloudinary.fifa.com/api/v1/picture/flags-sq-5/ITA?tx=c_fill,g_auto,q_auto,w_200",
"name":"Italy"
},
{
"position":7,
"flag_img":"https://cloudinary.fifa.com/api/v1/picture/flags-sq-5/ESP?tx=c_fill,g_auto,q_auto,w_200",
"name":"Spain"
},
{
"position":8,
"flag_img":"https://cloudinary.fifa.com/api/v1/picture/flags-sq-5/POR?tx=c_fill,g_auto,q_auto,w_200",
"name":"Portugal"
},
{
"position":9,
"flag_img":"https://cloudinary.fifa.com/api/v1/picture/flags-sq-5/MEX?tx=c_fill,g_auto,q_auto,w_200",
"name":"Mexico"
},
{
"position":10,
"flag_img":"https://cloudinary.fifa.com/api/v1/picture/flags-sq-5/NED?tx=c_fill,g_auto,q_auto,w_200",
"name":"Netherlands"
},
{
"position":11,
"flag_img":"https://cloudinary.fifa.com/api/v1/picture/flags-sq-5/DEN?tx=c_fill,g_auto,q_auto,w_200",
"name":"Denmark"
},
{
"position":12,
"flag_img":"https://cloudinary.fifa.com/api/v1/picture/flags-sq-5/GER?tx=c_fill,g_auto,q_auto,w_200",
"name":"Germany"
},
{
"position":13,
"flag_img":"https://cloudinary.fifa.com/api/v1/picture/flags-sq-5/URU?tx=c_fill,g_auto,q_auto,w_200",
"name":"Uruguay"
},
{
"position":14,
"flag_img":"https://cloudinary.fifa.com/api/v1/picture/flags-sq-5/SUI?tx=c_fill,g_auto,q_auto,w_200",
"name":"Switzerland"
},
{
"position":15,
"flag_img":"https://cloudinary.fifa.com/api/v1/picture/flags-sq-5/USA?tx=c_fill,g_auto,q_auto,w_200",
"name":"USA"
},
{
"position":16,
"flag_img":"https://cloudinary.fifa.com/api/v1/picture/flags-sq-5/CRO?tx=c_fill,g_auto,q_auto,w_200",
"name":"Croatia"
},
{
"position":17,
"flag_img":"https://cloudinary.fifa.com/api/v1/picture/flags-sq-5/COL?tx=c_fill,g_auto,q_auto,w_200",
"name":"Colombia"
},
{
"position":18,
"flag_img":"https://cloudinary.fifa.com/api/v1/picture/flags-sq-5/WAL?tx=c_fill,g_auto,q_auto,w_200",
"name":"Wales"
},
{
"position":19,
"flag_img":"https://cloudinary.fifa.com/api/v1/picture/flags-sq-5/SWE?tx=c_fill,g_auto,q_auto,w_200",
"name":"Sweden"
},
{
"position":20,
"flag_img":"https://cloudinary.fifa.com/api/v1/picture/flags-sq-5/SEN?tx=c_fill,g_auto,q_auto,w_200",
"name":"Senegal"
}
]

export default footballRanking;